import type { DeductionLog, InventoryItem } from "./types";

export const initialItems: InventoryItem[] = [
  {
    id: "iv1",
    name: "Composite syringe · A2",
    category: "Restorative",
    unit: "syringe",
    parMin: 6,
    parTarget: 12,
    stock: 4,
    vendor: "3M Filtek",
    unitCostSgd: 38,
    reorderQty: 12,
    status: "below_par",
    weeklyUsage: [2, 1, 3, 2, 2, 1, 3],
  },
  {
    id: "iv2",
    name: "Lignocaine 2% · 1.8ml",
    category: "Anesthesia",
    unit: "carpule",
    parMin: 50,
    parTarget: 100,
    stock: 32,
    vendor: "Septodont SG",
    unitCostSgd: 1.4,
    reorderQty: 100,
    status: "below_par",
    weeklyUsage: [12, 8, 14, 10, 11, 9, 13],
  },
  {
    id: "iv3",
    name: "Nitrile gloves · M",
    category: "PPE",
    unit: "box of 100",
    parMin: 8,
    parTarget: 16,
    stock: 6,
    vendor: "Top Glove",
    unitCostSgd: 14,
    reorderQty: 12,
    status: "below_par",
    weeklyUsage: [1, 1, 2, 1, 2, 1, 2],
  },
  {
    id: "iv4",
    name: "Cotton rolls · #2",
    category: "Disposables",
    unit: "box of 1000",
    parMin: 2,
    parTarget: 4,
    stock: 3,
    vendor: "Henry Schein SG",
    unitCostSgd: 22,
    reorderQty: 4,
    status: "low",
    weeklyUsage: [1, 0, 1, 1, 0, 0, 1],
  },
  {
    id: "iv5",
    name: "Suction tips",
    category: "Disposables",
    unit: "bag of 100",
    parMin: 3,
    parTarget: 6,
    stock: 5,
    vendor: "Henry Schein SG",
    unitCostSgd: 18,
    reorderQty: 6,
    status: "ok",
    weeklyUsage: [3, 2, 4, 2, 3, 2, 4],
  },
  {
    id: "iv6",
    name: "Bonding agent · Single Bond",
    category: "Restorative",
    unit: "bottle",
    parMin: 2,
    parTarget: 4,
    stock: 3,
    vendor: "3M",
    unitCostSgd: 88,
    reorderQty: 4,
    status: "ok",
    weeklyUsage: [0, 1, 0, 0, 1, 0, 1],
  },
  {
    id: "iv7",
    name: "FG diamond burs · round",
    category: "Restorative",
    unit: "pack of 5",
    parMin: 4,
    parTarget: 8,
    stock: 8,
    vendor: "Komet SG",
    unitCostSgd: 42,
    reorderQty: 8,
    status: "ok",
    weeklyUsage: [1, 0, 1, 0, 1, 0, 1],
  },
  {
    id: "iv8",
    name: "Sterilisation pouches · 90×260",
    category: "Sterilisation",
    unit: "box of 200",
    parMin: 2,
    parTarget: 4,
    stock: 4,
    vendor: "Crosstex",
    unitCostSgd: 36,
    reorderQty: 4,
    status: "ordered",
    weeklyUsage: [12, 10, 14, 11, 13, 9, 12],
    reorderEta: "Wed 30 Apr",
  },
];

export const todaysDeductions: DeductionLog[] = [
  {
    id: "d1",
    time: "09:30",
    patientName: "Demo patient 101",
    procedure: "Composite filling · 36",
    itemsDeducted: [
      { name: "Composite syringe · A2", qty: 1, unit: "syringe" },
      { name: "Bonding agent · Single Bond", qty: 1, unit: "bottle" },
      { name: "Lignocaine 2% · 1.8ml", qty: 2, unit: "carpule" },
      { name: "Cotton rolls · #2", qty: 4, unit: "roll" },
    ],
  },
  {
    id: "d2",
    time: "10:30",
    patientName: "Demo patient 102",
    procedure: "Polish & scale",
    itemsDeducted: [
      { name: "Nitrile gloves · M", qty: 1, unit: "pair" },
      { name: "Cotton rolls · #2", qty: 2, unit: "roll" },
      { name: "Suction tips", qty: 1, unit: "tip" },
    ],
  },
  {
    id: "d3",
    time: "11:30",
    patientName: "Demo patient 103",
    procedure: "RCT · 36 · access cavity",
    itemsDeducted: [
      { name: "Lignocaine 2% · 1.8ml", qty: 3, unit: "carpule" },
      { name: "FG diamond burs · round", qty: 1, unit: "bur" },
      { name: "Cotton rolls · #2", qty: 6, unit: "roll" },
    ],
  },
];
